### ISSUE TITLE
Feature request: Build in voice message

### ISSUE THREAD

**Issue by playforvoices1** [nitanmarcel/cinny-click-packaging#11]
Is it possible to create the Cinny app with a build in voice message feature, like TelePorts has? The Cinny app itself is able to handle .ogg files as attachment without problems. But you have it to create first with another app. :(

**Comment by nitanmarcel** [comment]
Other issues or feature requests that are not related to the packaging for ubuntu touch needs to be reported in thr cinny repo https://github.com/cinnyapp/cinny/issues

**Comment by playforvoices1** [comment]
It seems there is a misunderstanding. I ask directly for the UT based app. There is no such feature in the recent version of the original Cinny. And I think they will not seen there anyway. The voice message has to create locally at the phone. So my question was to add this functionality directly inside the code of Cinny UT version.

**Comment by nitanmarcel** [comment]
> It seems there is a misunderstanding. I ask directly for the UT based app. There is no such feature in the recent version of the original Cinny. And I think they will not seen there anyway. The voice message has to create locally at the phone. So my question was to add this functionality directly inside the code of Cinny UT version.

That kind of feature needs to be added to cinny first then if there are any issues on UT side it needs to be [patched](https://github.com/nitanmarcel/cinny-click-packaging/tree/main/patches). Cinny has no support yet for recording voice messages and if they add it I suppose it will also work on UT without any changes
