### ISSUE TITLE
No Emoji verification

### ISSUE THREAD

**Issue by playforvoices1** [nitanmarcel/cinny-click-packaging#12]
Currently, it's not possible to verify a new device with Emoji support on UT. You have to type in the Security Key.

**Comment by nitanmarcel** [comment]
> Currently, it's not possible to verify a new device with Emoji support on UT. You have to type in the Security Key.

~~Does app.cinny.in works (you can use it on the PC's browser since it's broken in morph.~~

~~They were implemented in https://github.com/cinnyapp/cinny/commit/2867bb3bc3253957ab3e5613cf0b2b2791cb84e4 please check if they work in the browser :)~~

They seem to work fine on browser. Checking out on UT

**Comment by playforvoices1** [comment]
I've checked it back on browser. Emoji appears but after the matching Emojis the security key is required. So it's a problem with Cinny itself.

**Comment by nitanmarcel** [comment]
> Currently, it's not possible to verify a new device with Emoji support on UT. You have to type in the Security Key.

Working both in browser and in Ubuntu Touch

![image](https://user-images.githubusercontent.com/41646249/174567561-1f3c22ce-7bfd-453b-90e4-dcdc3cf16dad.png)

**Comment by nitanmarcel** [comment]
> I've checked it back on browser. Emoji appears but after the matching Emojis the security key is required. So it's a problem with Cinny itself.

Are you using a custom synapse server? That might be the issue as I got my session verified just fine without any security key.

![image](https://user-images.githubusercontent.com/41646249/174568164-1f5a9855-67fe-48b0-9cba-b7165719f41d.png)

Another place to check is with other matrix clients which support emoji verifications like [element](https://app.element.io/)

**Comment by playforvoices1** [comment]
It seems I had an issue here. No custom synapse server. Just registered with matrix.org like the other clients. I try it on a different machine later then.

**Comment by nitanmarcel** [comment]
> It seems I had an issue here. No custom synapse server. Just registered with matrix.org like the other clients. I try it on a different machine later then.

Good luck. If the issue only happens to cinny open an issue on their repo at https://github.com/cinnyapp/cinny

Closing this issue here :)

**Comment by ajbura** [comment]
@nitanmarcel @playforvoices1 It ask for security it when it doesn't have access to secret storage so that it can get keys from storage to sign in. Element also do that for the same reason. And it's a one time thing per session.
