### ISSUE TITLE
I can't login to my homeserver

### ISSUE THREAD

**Issue by Llazcanoster** [nitanmarcel/cinny-click-packaging#13]
# Please follow the general troubleshooting steps first:

- [X] This bug is not reproducible on https://app.cinny.in
- [ ] This bug is not mentioned in any issues here or in the [upstream repository](https://github.com/cinnyapp/cinny)

**Describe the bug**
Although in the web version of cinny I can, in the clickable version, can't login to my homeserver.

**To Reproduce**
1. Go to log page
2. insert your custom homeserver
3. See error "Unable to connect, Please check yout input"

**Expected behavior**
Login to my homeserver with my username and password

**Screenshots**

![PXL_20220801_170322395](https://user-images.githubusercontent.com/84098622/182180013-a18eccdb-d380-411b-8e0e-6e0eec165d53.jpg)
![Screenshot_20220801_170523](https://user-images.githubusercontent.com/84098622/182180331-af391733-ebce-4a98-81a4-3b6f47a5b9d8.png)

**Additional context**
I have added my homeserver to config.json, but I get the same error

**Comment by nitanmarcel** [comment]
Can you connect to the same server using app.cinny.in ?

**Comment by Llazcanoster** [comment]
Yes, I can

**Comment by nitanmarcel** [comment]
> Yes, I can

I see. If you can send me some logs it would be nice. I'm currently busy with some things but I'll look into your issue this week :)

**Comment by Llazcanoster** [comment]
Ok great, thank you very much, but where can I find the logs concerning Cinny? I've been looking in var/log/ and I don't see anything, sorry :(

**Comment by nitanmarcel** [comment]
> Ok great, thank you very much, but where can I find the logs concerning Cinny? I've been looking in var/log/ and I don't see anything, sorry :(

`~/.cache/upstart/application-click-cinny.nitanmarcel_cinny_2.0.4notificationfix1.log`

**Comment by nitanmarcel** [comment]
I see what might be the issue. The issue is with your server ssl certificate. Probably we just don't have the following popup to ask the user if they should proceed with the connection or not, and it fails to do so.
![image](https://user-images.githubusercontent.com/41646249/182203177-c9e00928-c33a-4210-9146-e14fbcdee10a.png)

**Comment by Llazcanoster** [comment]
This only happens in morph, but if you add in front https:// it works correctly.

**Comment by Llazcanoster** [comment]
> > Ok great, thank you very much, but where can I find the logs concerning Cinny? I've been looking in var/log/ and I don't see anything, sorry :(
> 
> `~/.cache/upstart/application-click-cinny.nitanmarcel_cinny_2.0.4notificationfix1.log`
I do not have this application :0))))

![PXL_20220801_190956407](https://user-images.githubusercontent.com/84098622/182205016-f6e1b244-b0e1-488e-974a-7274a2bb33fe.jpg)

Sorry for the inconvenience

**Comment by nitanmarcel** [comment]
> This only happens in morph, but if you add in front https:// it works correctly.

It doesn't show the dialog the second time because you've already clicked "Proceed anyway". If you open a "New private window" in morph will still show the dialog even if you use https before :)

**Comment by Llazcanoster** [comment]
I see something is up with that, but it only happens to me with Morph, in Firefox, Chrome, etc. in different OS, my TrustCor Systems certificate does not throw errors.

**Comment by Llazcanoster** [comment]
I think my problem has more to do with Morph and the certifier than with Cinny-clickable.
For my part we can consider the case closed. Thank you very much for your time and congratulations for the work!

**Comment by nitanmarcel** [comment]
> I think my problem has more to do with Morph and the certifier than with Cinny-clickable. For my part we can consider the case closed. Thank you very much for your time and congratulations for the work!

I'll probably see in adding the dialog morph has if someone has the same issue

**Comment by Llazcanoster** [comment]
Perfect, thank you!
