### ISSUE TITLE
SSO login not working

### ISSUE THREAD

**Issue by oelabb** [nitanmarcel/cinny-click-packaging#17]
# Please follow the general troubleshooting steps first:

This bug is not reproducible on https://app.cinny.in

**Describe the bug**
The link from morph, opens the app but nothing happens..

**To Reproduce**
1. Go to cinny app
2. Click on login with OIDC
3. In morph add username and pass
4. Next, in morph click in the link to open cinny app

**Expected behavior**
login in Cinny

**Comment by nitanmarcel** [comment]
Thanks. Should be fixed in the next version.

**Comment by oelabb** [comment]
Thank you very much. now it works
