### ISSUE TITLE
Login with OIDC does not work

### ISSUE THREAD

**Issue by sergiusens** [nitanmarcel/cinny-click-packaging#21]
- [x] This bug is not reproducible on https://app.cinny.in
- [x] This bug is not mentioned in any issues here or in the [upstream repository](https://github.com/cinnyapp/cinny)

**Describe the bug**
Clicking on "Login with OIDC" does nothing (required for Element One)
![image](https://user-images.githubusercontent.com/1146853/222841252-8825bd9f-3bb5-44ee-ae15-c1e48ce53606.png)

**To Reproduce**
1. Open the app
2. Setup the matrix server to one.ems.host
3. Tap on "Login with OIDC"
4. Nothing happens

**Expected behavior**
Should be redirected to https://id.element.io to login

**Comment by nitanmarcel** [comment]
Never saw that login type so I never implemented it. Doesn't open morph?

**Comment by sergiusens** [comment]
It does not open Morph. It was my expectation. Luckily, you don't need an account to try yourself. It does work with Cinny on my Firefox Desktop session.

**Comment by equareo** [comment]
This is odd, because I use Element one just fine with Cinny. Maybe you have adblock installed? I use it daily on Focal, but it also worked fine in Xenial in November when i tried it.

**Comment by sergiusens** [comment]
I have no ad block installed. This is a fresh install. I am running 20.04 though.Can you perhaps try cleaning up the cache and logging in again?

**Comment by equareo** [comment]
Just did, it opens up the morph browser, and works fine. I'm on 20.04, devel channel.

**Comment by sergiusens** [comment]
OK, thanks, I just tried again and it worked! I have updated the image since this bug report.

Thanks for corroborating
