### ISSUE TITLE
[UT only] send/emoji buttons badly visible in dark mode

### ISSUE THREAD

**Issue by Danfro** [nitanmarcel/cinny-click-packaging#6]
Only in the UT version of Cinny the send/emoji buttons are badly visible (see screenshot). Apparently in original Cinny web version that is not the case. They should be white/bright color on dark background.

![image](https://user-images.githubusercontent.com/37637312/169324950-bfc29621-f2bd-460c-8724-e5a15ea069cb.png)

**Comment by nitanmarcel** [comment]
Issues with the chrome engine UT uses atm and css mask. The patch to fix them is incomplete and currently there's no point on completing since there's a MR that will push a newer chrome engine and fix these issues. [MR](https://gitlab.com/ubports/core/packaging/qtwebengine/-/merge_requests/8)

**Comment by Danfro** [comment]
Ok, good. Sounds like you know what needs to be done and you are aware of the problem. :+1: 

I suggest we leave this issue open for reference and to make sure we don't forget. But we know a fix does depend on other things getting merged first.

**Comment by nitanmarcel** [comment]
An update on this. It should be fixed in the development channel, and later in the following weeks on RC.

Also in stable channel in the next 1-2 months whenever ubports team decides to push the next OTA.
