### ISSUE TITLE
Crash just after loggin

### ISSUE THREAD

**Issue by lutin11** [nitanmarcel/cinny-click-packaging#7]
[application-click-cinny.nitanmarcel_cinny_2.0.3.zip](https://github.com/nitanmarcel/cinny-click-packaging/files/8765331/application-click-cinny.nitanmarcel_cinny_2.0.3.zip)

**Comment by nitanmarcel** [comment]
There's no error related to the crash there. Please try to log in with [app.cinny.in](https://app.cinny.in/) and see if it still crashes.

**Comment by nitanmarcel** [comment]
Closed for inactivity. Also I'm not getting this issue and I can log it without any problems.
