### ISSUE TITLE
No sending of multimedia files

### ISSUE THREAD

**Issue by digi6622** [nitanmarcel/cinny-click-packaging#8]
On Vollaphone (Ubuntu Touch - fresh installation) Cinny doesn't send pictures, files an so on. I can choose a self made photo and by clicking send it appears a small icon of the photo and a progress bar. But the photo wasn't send.

**Comment by nitanmarcel** [comment]
> On Vollaphone (Ubuntu Touch - fresh installation) Cinny doesn't send pictures, files an so on. I can choose a self made photo and by clicking send it appears a small icon of the photo and a progress bar. But the photo wasn't send.

Does it happen inside an encrypted chat?

Also test if app.cinny.in has the same issue

**Comment by nitanmarcel** [comment]
Also after the file has loaded. Did you pressed the send button again?

**Comment by digi6622** [comment]
Yes, it was an encrypted chat.
I wanted to test the webapp of chinny but there is a problem with displaying of icons in the app (just squares instead of slide switches and checkboxes).
And yes, I pressed the send button again.

**Comment by nitanmarcel** [comment]
> Yes, it was an encrypted chat. I wanted to test the webapp of chinny but there is a problem with displaying of icons in the app (just squares instead of slide switches and checkboxes). And yes, I pressed the send button again.

you should still be able to log in. anyway. I'll look at your issue soon

**Comment by digi6622** [comment]
Thanks a lot for your nice support.
I tried your hints again with following:
The first time I pushed the send button cinny shows "send..." (but nothing happens)
The second time I pressed send cinny shows "Uploading..." (but nothing happens).
Take your time with the support and stay relaxed.

**Comment by digi6622** [comment]
Sorry, it's no issue of cinny. After seeing that other clients could not send files either, I came across the solution after a long search: My matrix synapse had too low file size limitation. I increase it in nginx.conf (client_max_body_size). Now everything is fine.
