### ISSUE TITLE
Predictive text input

### ISSUE THREAD

**Issue by playforvoices1** [nitanmarcel/cinny-click-packaging#9]
Is it possible to make the predictive text input available in Cinny on UT? Currently, there is just the regular keyboard useable.

**Comment by nitanmarcel** [comment]
No idea honestly. If regular web pages in morph can use predictive text input then probably yes.

We're using an webapp on top of QT's web engine so if the text prediction doesn't work in morph probably won't work on cinny too

**Comment by playforvoices1** [comment]
Ah, okay. So if you use a web app, there is no predictive text input. A problem by UT itself.

**Comment by nitanmarcel** [comment]
> Ah, okay. So if you use a web app, there is no predictive text input. A problem by UT itself.

Yes. Cinny is practically a self hosted instance of https://app.cinny.in adapted to work with UT which is ran with a localhost server and the QTWebEngineView.
